language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head

notifications:
  disabled: true

script:
  - bundle exec rspec

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - sudo apt-get update -qq
  - gem install wwtd
  - sudo apt-get install libicu-dev -yqq
  - git init --bare spec/utils/wiki.git

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails3213.gemfile
  - gemfiles/rails4.gemfile

deploy:
  provider: rubygems
  api_key:
    secure: nn8ZUGQaTNvfFnMyWZafSGcN513QxZsW3TYx15MpcFQJNLxUfGFWBO2laBIUBuYM0tz1EvLU3C40nh1cFQfONELufKfQFPdwVqICCoGYp3K6+R7DIo3BCUVrOmZh8dSrWNQgn6HNPDq/5kBflxw87l4sLL5uJZpSzfasYyBgId0=
  gem: gollum_rails
  on:
    repo: nirnanaaa/gollum_rails
